# Generated by Django 6.1.1 on 2026-09-12 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('push_preview', models.CharField(max_length=255)),
                ('target_classification', models.CharField(blank=True, max_length=255, null=True)),
                ('needs_ack', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('queued', 'Queued'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('confirmed_content_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='callouts.local')),
            ],
        ),
    ]
