# Generated by Django 6.1.1 on 2026-09-12 15:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callouts', '0002_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification_snapshot', models.CharField(max_length=255)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('rsvp', models.CharField(blank=True, max_length=255, null=True)),
                ('rsvp_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='callouts.announcement')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcement_recipients', to='callouts.local')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcement_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('announcement', 'member'), name='unique_announcement_member')],
            },
        ),
    ]
