# Generated by Django 6.1.1 on 2026-09-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callouts', '0003_announcementrecipient'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='announcementrecipient',
            constraint=models.CheckConstraint(condition=models.Q(('acknowledged_at__isnull', True), ('read_at__isnull', False), _connector='OR'), name='acknowledged_requires_read'),
        ),
    ]
