# Generated by Django 6.1.1 on 2026-09-12 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callouts', '0004_announcementrecipient_acknowledged_requires_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('acknowledged_count', models.PositiveIntegerField(default=0)),
                ('coming_count', models.PositiveIntegerField(default=0)),
                ('cant_come_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='callouts.announcement')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcement_stats', to='callouts.local')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('target_count__gte', 0), ('sent_count__gte', 0), ('failed_count__gte', 0), ('read_count__gte', 0), ('acknowledged_count__gte', 0), ('coming_count__gte', 0), ('cant_come_count__gte', 0)), name='announcement_stats_counts_non_negative')],
            },
        ),
    ]
