# Generated by Django 6.1.1 on 2026-09-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callouts', '0005_announcementstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementrecipient',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='claimed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcementrecipient',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
