# Generated by Django 6.1.1 on 2026-09-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('callouts', '0006_announcementrecipient_attempt_count_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(condition=models.Q(('is_active', True), ('status', 'active')), fields=['local', 'id'], name='member_active_local_id_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(condition=models.Q(('is_active', True), ('status', 'active')), fields=['local', 'classification', 'id'], name='member_active_local_class_idx'),
        ),
    ]
